name: Tikal
markdown: redcarpet
highlighter: true
exclude:
  - jekyll-import-0.2.0
baseurl: /
nav_links: [ "/about", "/solutions", "/careers", "/events", "/contact" ]
assets:
  debug: true
  baseurl: /assets
  compress:
    css:  sass
    js:   uglifier
    debug: true
paginate: 10
prose:
  rooturl: ''
  siteurl: 'http://www.tikalk.com'
  media: '_assets/images/default'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "text"
          value: "post"
          placeholder: "Your Github username"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Java"
              value: "java"
            - name: "Javascript"
              value: "javascript"
            - name: "Ruby"
              value: "ruby"
            - name: "DevOps"
              value: "devops"
            - name: "Android"
              value: "android"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
          placeholder: "/[domain]/[title]"
